SELECT SS_TRAMITES.I_SS AS 'ss',
       SS_TRAMITES.ENTRADA AS 'data_hora',
       SS_TRAMITES.I_SS_TRAMITES AS 'tramite',
       USUARIO.NOME AS 'analista',
       CLASSIFICACAO.DESCRICAO AS 'classificacao',
       MODULOS.NOME AS 'modulo',
       TOPICOS.TOPICO AS 'topico',
       MES = MONTH(SS_TRAMITES.ENTRADA)
 FROM BETHADBA.SS_TRAMITES 
 JOIN BETHADBA.USUARIOS AS USUARIO
   ON USUARIO.I_USUARIOS = SS_TRAMITES.I_USUARIOS 
 JOIN BETHADBA.SS
   ON SS.I_SS = SS_TRAMITES.I_SS
 JOIN BETHADBA.SSS_CLASSIFICACOES AS CLASSIFICACAO
   ON CLASSIFICACAO.I_SSS_CLASSIFICACOES = SS.I_SSS_CLASSIFICACOES
 JOIN BETHADBA.MODULOS AS MODULOS
   ON MODULOS.I_MODULOS = SS.I_MODULOS AND MODULOS.I_SISTEMAS = SS.I_SISTEMAS
 JOIN BETHADBA.TOPICOS_SUPORTES AS TOPICOS
   ON TOPICOS.I_MODULOS = SS.I_MODULOS AND TOPICOS.I_SISTEMAS = SS.I_SISTEMAS AND TOPICOS.I_TOPICOS_SUPORTES = SS.I_TOPICOS_SUPORTES
WHERE ANALISTA IN ('Higor Duarte de Souza', 'Thais Marques Madeira', 'Maicon Antunes Luiz', 'Samuel Goncalves', 'Guilherme Cardoso Possenti', 'Rodrigo Rodrigues Domingos', 'Leandro Cemin Silvestre', 'Jardel Galvao Rodrigues', 'Davi Jose Salvaro Pasetto', 'Mauricio Scariot Rosso')
  AND SS_TRAMITES.ENTRADA BETWEEN ? AND ?
  AND SS_TRAMITES.SITUACAO IN (8,27)
  
  ORDER BY ANALISTA, SS_TRAMITES.ENTRADA ASC