SELECT RESPOSTA_DESENV.I_SS AS 'ss',
       ENCAMINHAMENTO_INCORRETO.ENTRADA AS 'data_hora',
       ENCAMINHAMENTO_INCORRETO.I_SS_TRAMITES AS 'tramite',
       USUARIO.NOME AS 'analista',
       CLASSIFICACAO.DESCRICAO AS 'classificacao',
       MODULOS.NOME AS 'modulo',
       TOPICOS.TOPICO AS 'topico'
  FROM BETHADBA.SS_TRAMITES AS RESPOSTA_DESENV
       JOIN BETHADBA.SS_TRAMITES AS ENCAMINHAMENTO_INCORRETO
       ON ENCAMINHAMENTO_INCORRETO.I_SS = RESPOSTA_DESENV.I_SS
       JOIN BETHADBA.USUARIOS AS USUARIO
       ON USUARIO.I_USUARIOS = ENCAMINHAMENTO_INCORRETO.I_USUARIOS
       JOIN BETHADBA.SS
       ON SS.I_SS = RESPOSTA_DESENV.I_SS
       JOIN BETHADBA.SSS_CLASSIFICACOES AS CLASSIFICACAO
       ON CLASSIFICACAO.I_SSS_CLASSIFICACOES = SS.I_SSS_CLASSIFICACOES
       JOIN BETHADBA.MODULOS AS MODULOS
       ON MODULOS.I_MODULOS = SS.I_MODULOS AND MODULOS.I_SISTEMAS = SS.I_SISTEMAS
       JOIN BETHADBA.TOPICOS_SUPORTES AS TOPICOS
       ON TOPICOS.I_MODULOS = SS.I_MODULOS AND TOPICOS.I_SISTEMAS = SS.I_SISTEMAS AND TOPICOS.I_TOPICOS_SUPORTES = SS.I_TOPICOS_SUPORTES
 WHERE RESPOSTA_DESENV.TIPO_ENCAMINHAMENTO = 1
   AND ENCAMINHAMENTO_INCORRETO.I_SS_TRAMITES = (SELECT MAX(TRAMITE.I_SS_TRAMITES)
                                                   FROM BETHADBA.SS_TRAMITES AS TRAMITE
                                                  WHERE TRAMITE.I_SS_TRAMITES < RESPOSTA_DESENV.I_SS_TRAMITES
                                                    AND TRAMITE.SITUACAO IN (8,27,6) /*Aguardando Resposta Desenvolvimento*/
                                                    AND TRAMITE.I_SS = RESPOSTA_DESENV.I_SS
                                                    AND DATE(TRAMITE.ENTRADA) BETWEEN ? AND ?)
    AND ANALISTA IN ('Higor Duarte de Souza', 'Thais Marques Madeira', 'Maicon Antunes Luiz', 'Samuel Goncalves', 'Guilherme Cardoso Possenti', 'Rodrigo Rodrigues Domingos', 'Leandro Cemin Silvestre', 'Jardel Galvao Rodrigues', 'Davi Jose Salvaro Pasetto', 'Mauricio Scariot Rosso')
ORDER BY ENCAMINHAMENTO_INCORRETO.ENTRADA